### ISSUE TITLE
Error when generate schema files

### ISSUE THREAD

**Issue by danielfttorres** [danielfeelfine/graphql-relay-server#1]
When run `$ yarn update-schema` got this error:

```
var directives = schema.getDirectives().filter(function (directive) {
                       ^

TypeError: Cannot read property 'getDirectives' of undefined
    at printFilteredSchema (~/graphql-relay-server/node_modules/graphql/utilities/schemaPrinter.js:70:26)
    at printSchema (~/graphql-relay-server/node_modules/graphql/utilities/schemaPrinter.js:44:10)
    at Object.<anonymous> (~/graphql-relay-server/scripts/updateSchema.js:26:3)
```

**Comment by danjambur** [comment]
@danielfeelfine how did you fix this issue?

**Comment by danielfeelfine** [comment]
@danjambur just update to [Relay 1.6.0](https://github.com/facebook/relay/releases/tag/v1.6.0) fixes the issue.

**Comment by danielfttorres** [comment]
@danjambur heres the fix: https://github.com/danielfeelfine/graphql-relay-server/commit/9c5b42cac80482df9258fbaf725c1cd65cd9c35c
